# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='car_classes',
        ),
        migrations.AddField(
            model_name='track',
            name='car_classes',
            field=models.ManyToManyField(to='vehicles.Vehicle'),
        ),
    ]
