# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_auto_20161122_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptime',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='laptime',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='laptime',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
