# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0009_auto_20161123_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptime',
            name='pc_60fps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laptime',
            name='recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='platform',
            field=models.CharField(choices=[('pc', 'PC'), ('ps4', 'PS 4'), ('xb1', 'XBox One'), ('ps3', 'PS 3'), ('xb3', 'XBox 360')], default='pc', max_length=8),
        ),
    ]
