# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20161118_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='car_classes',
            field=models.ManyToManyField(to='vehicles.VehicleClass'),
        ),
    ]
