# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 15:58
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_auto_20161118_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
