# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0008_track_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='game_mode',
            field=models.CharField(choices=[('stunt', 'stunt race'), ('land', 'land race')], default='stunt', max_length=8),
        ),
        migrations.AlterField(
            model_name='track',
            name='route_type',
            field=models.CharField(choices=[('l', 'laps'), ('p', 'point to point')], default='l', max_length=1),
        ),
    ]
