# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0011_auto_20161129_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptime',
            name='recorded',
            field=models.DateField(),
        ),
    ]
