# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0013_auto_20161201_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptime',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
