# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0014_auto_20161206_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptime',
            name='recorded',
            field=models.DateField(null=True),
        ),
    ]
