# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_staggeredstartrace_laptimes'),
        ('tracks', '0015_auto_20161209_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptime',
            name='staggeredstartevent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.StaggeredStartRace'),
        ),
    ]
