# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0016_laptime_staggeredstartevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptime',
            name='start_dt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
