# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0017_laptime_start_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptime',
            name='seconds',
        ),
        migrations.RemoveField(
            model_name='laptime',
            name='seconds_per_km',
        ),
        migrations.RemoveField(
            model_name='laptime',
            name='staggeredstartevent',
        ),
        migrations.RemoveField(
            model_name='laptime',
            name='start_dt',
        ),
        migrations.AddField(
            model_name='laptime',
            name='millis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laptime',
            name='millis_per_km',
            field=models.IntegerField(default=0),
        ),
    ]
