# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0018_auto_20161211_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='reference_track',
            field=models.BooleanField(default=False, help_text='Is this a reference track for laptimes?'),
        ),
    ]
