# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0019_track_reference_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptime',
            name='comment',
            field=models.TextField(default='', null=True),
        ),
    ]
