# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0022_track_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptime',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
