# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 14:56
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0023_auto_20170117_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
