# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0026_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
