# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0027_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='platform',
            field=models.CharField(choices=[('pc', 'PC'), ('ps4', 'PS 4'), ('xb1', 'XBox One')], default='pc', max_length=8),
        ),
    ]
