# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0028_auto_20170308_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptime',
            options={'ordering': ['-pk']},
        ),
    ]
