# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0029_auto_20170312_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptime',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
