# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0030_auto_20170326_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='num_fast_chicanes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='num_fast_turns',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='num_hairpins',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='num_slow_chicanes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='num_slow_turns',
            field=models.SmallIntegerField(default=0),
        ),
    ]
