# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['classes__name', 'name']},
        ),
    ]
