# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20161201_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='lsgp_seconds_per_km',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lsgp_seconds_per_km_stock',
            field=models.FloatField(null=True),
        ),
    ]
