# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20161205_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='lsgp_seconds_per_km',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='lsgp_seconds_per_km_stock',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lsgp_millis_per_km',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lsgp_millis_per_km_stock',
            field=models.IntegerField(null=True),
        ),
    ]
