# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20161211_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='lsgp_millis_per_km',
            new_name='cc_millis_per_km',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='lsgp_millis_per_km_stock',
            new_name='cc_millis_per_km_stock',
        ),
    ]
