# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20170102_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cc_laptime_millis',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='cc_millis_per_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
