# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20170104_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
