# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_topspeed_kmh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='cc_laptime_millis',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
