# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_auto_20170307_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
