# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rscname',
            new_name='username',
        ),
    ]
