# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20170104_1020'),
        ('players', '0006_auto_20161222_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='defaultspeedmultiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle'),
        ),
    ]
