# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
