# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20161205_0844'),
        ('events', '0003_auto_20161206_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='staggeredstartrace',
            name='vehicle_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.VehicleClass'),
        ),
    ]
