# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_staggeredstartrace_vehicle_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staggeredstartrace',
            name='laptimes',
        ),
    ]
