# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_staggeredstartrace_laptimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='staggeredstartrace',
            name='start_dt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
