# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0018_auto_20161211_1307'),
        ('vehicles', '0004_auto_20161211_1307'),
        ('events', '0006_staggeredstartrace_start_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSRParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('untuned', models.BooleanField(default=False, help_text='is this in an untuned car?')),
                ('estimated_net_millis', models.IntegerField(null=True)),
                ('laptime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.Laptime')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('staggeredstartrace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.StaggeredStartRace')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle')),
            ],
        ),
    ]
