# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_ssrparticipation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssrparticipation',
            options={'ordering': ('player__username',)},
        ),
        migrations.AlterField(
            model_name='ssrparticipation',
            name='estimated_net_millis',
            field=models.IntegerField(help_text='according to calculations the estimated total racing net time for the whole race.', null=True),
        ),
    ]
