# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_staggeredstartrace_start_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staggeredstartrace',
            old_name='start_dt',
            new_name='start_timestamp',
        ),
    ]
