# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20161213_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='staggeredstartrace',
            name='per_overtake_deficit',
            field=models.FloatField(default=0.6, null=True),
        ),
    ]
