# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_staggeredstartrace_per_overtake_deficit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staggeredstartrace',
            name='per_overtake_deficit',
        ),
        migrations.AddField(
            model_name='staggeredstartrace',
            name='per_overtake_deficit_millis',
            field=models.IntegerField(default=600, null=True),
        ),
    ]
