# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20161213_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssrparticipation',
            options={'ordering': ('start_timestamp', 'player__username')},
        ),
        migrations.AlterField(
            model_name='staggeredstartrace',
            name='status',
            field=models.CharField(choices=[('p', 'planning'), ('i', 'initializing'), ('r', 'running'), ('f', 'finished')], default='i', max_length=1),
        ),
    ]
