# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_auto_20161213_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaggeredPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(choices=[('pc', 'PC'), ('ps4', 'PS 4'), ('xb1', 'XBox One'), ('ps3', 'PS 3'), ('xb3', 'XBox 360')], default='pc', max_length=8)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='staggeredstartrace',
            name='number_in_playlist',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staggeredstartrace',
            name='staggeredplaylist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.StaggeredPlaylist'),
        ),
    ]
