# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20161220_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staggeredstartrace',
            name='status',
            field=models.CharField(choices=[('p', 'planning'), ('i', 'initializing'), ('r', 'running'), ('f', 'finished')], default='p', max_length=1),
        ),
    ]
