# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20170105_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssrparticipation',
            name='estimated_net_millis',
        ),
        migrations.AddField(
            model_name='ssrparticipation',
            name='estimated_laptime',
            field=models.IntegerField(help_text='according to calculations the estimated total racing net time for one lap.', null=True),
        ),
        migrations.AlterField(
            model_name='staggeredstartrace',
            name='laps',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
