# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20170112_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='staggeredstartrace',
            name='algorithm',
            field=models.CharField(choices=[('SA', 'Slow Assist'), ('PF', 'Photo Finish'), ('SO', 'Standard Only')], default='SA', max_length=2),
        ),
    ]
