# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20170208_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitassistant',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pitassistant',
            name='title',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ssrparticipation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle'),
        ),
    ]
