# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0025_pitlogentry_pitapitstop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitapitstop',
            name='pitaparticipation',
        ),
        migrations.RenameField(
            model_name='pitassistant',
            old_name='duration_seconds',
            new_name='pitstop_seconds',
        ),
        migrations.RemoveField(
            model_name='pitassistant',
            name='ingame_start_at_seconds',
        ),
        migrations.RemoveField(
            model_name='pitassistant',
            name='num_pitstops',
        ),
        migrations.RemoveField(
            model_name='pitlogentry',
            name='pitapitstop',
        ),
        migrations.AddField(
            model_name='pitassistant',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pitlogentry',
            name='entrytype',
            field=models.CharField(choices=[('p', 'pitstop'), ('c', 'comment'), ('y', 'yellow flag'), ('g', 'green flag')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='pitlogentry',
            name='for_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PitAPitstop',
        ),
    ]
