# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20170224_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitassistant',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
