# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0030_auto_20170326_1734'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0011_auto_20170307_0759'),
        ('events', '0027_auto_20170227_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotlapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Track')),
                ('vehicles', models.ManyToManyField(related_name='vehicles', to='vehicles.Vehicle')),
            ],
        ),
    ]
