# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_hotlapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotlapping',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotlapping',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
