# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20170502_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotlapping',
            name='closing_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
