# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_hotlapping_closing_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotlapping',
            name='divisions_text',
            field=models.TextField(default='10:Top Ten\n18:Regular players\n50:Reserves'),
        ),
    ]
