# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0030_auto_20170326_1734'),
        ('events', '0031_hotlapping_divisions_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotlappingLaptime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('hotlapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Hotlapping')),
                ('laptime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Laptime')),
            ],
        ),
        migrations.AddField(
            model_name='hotlapping',
            name='entries',
            field=models.ManyToManyField(through='events.HotlappingLaptime', to='tracks.Laptime'),
        ),
    ]
