# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20170516_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotlapping',
            name='divisions_text',
            field=models.TextField(default='10:Top Ten\n20:Rest of the starting grid\n999:Not fast enough'),
        ),
    ]
