# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20170607_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotlapping',
            options={'ordering': ('-end_date', 'pk')},
        ),
    ]
