# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_hotlapping_time_period_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotlapping',
            name='webhook_url',
            field=models.URLField(null=True),
        ),
    ]
