# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 13:51
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20161120_1151'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
