# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20161122_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(help_text='Please use your RSC name.', max_length=256, unique=True),
        ),
    ]
